### ISSUE TITLE
SendCommandAsync is gone from FtpClient?

### ISSUE THREAD

**Issue by AK107** [sparkeh9/CoreFTP#12]
Hi.

The last release drops subj, i.e. moves it to the FtpControlStream, but 
But i need it to send custom commands, for example GetModificationTime (MDTM) or many other.

Can you share it?

p.s. one more question about:

"Microsoft.Extensions.Caching.Abstractions": "1.0.0",
"Microsoft.Extensions.Caching.Memory": "1.0.0",
"Microsoft.Extensions.Logging.Abstractions": "1.0.0"

this is depends from **FULL** NETStandard.Library

it is really necessary libraries? because in pure .net project (_not_ net.standard) its pull all (20+) net.standard libs.

**Comment by sparkeh9** [comment]
Hi - this was omitted when refactoring. It has now been added back in @ v1.3.3 😄 
Please see https://www.nuget.org/packages/CoreFtp/1.3.3

Regarding the listed dependencies - CoreFTP is aimed at the NETStandard API surface, so this is expected if being used in .NET Framework.

The caching is used in DNS lookup, and the logging is used throughout.  If you can think of a way to stop lots of packages being included for .NET Framework while still providing the same level of functionality then by all means, issue a pull request.

NuGet is now a first class citizen and suddenly everything is now a NuGet package. The amount of packages required for inclusion in many libraries has gone up dramatically; While this is a bit overwhelming, I don't think this is necessarily a problem.  In contrast to the monolithic .NET Framework, this "everything a package" makes apps much more lean at runtime.
