### ISSUE TITLE
CoreFTP in Universal Windows app

### ISSUE THREAD

**Issue by CriticalCauchy** [sparkeh9/CoreFTP#20]
Hi,
I'd like to use CoreFTP in my Universal Windows app (UWP).

I created a .NET Core class library and added CoreFTP 1.3.4 via NuGet. Then in my UWP app, I added a reference to the library build (.dll). The UWP project.json looks like this:
```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.0",
    "Newtonsoft.Json": "9.0.1",
    "Template10": "1.1.12"
  },
  "frameworks": {
    "uap10.0": { "imports": "netstandard1.4" }
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```
I added  "imports": "netstandard1.4" because netstandard 1.5 or 1.6 isn't working. 
When I try to create a class from the lib, I receive this error:
> Could not load file or assembly 'CoreFtp, Version=1.3.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

What can I do to use this library in my UWP app?
Thank you for your help!

**Comment by sparkeh9** [comment]
I'm afraid I know nothing about UWP, but I can tell you that the minimum netstandard version is 1.3, so any version greater than that should be supported.

Whenever I see "Could not load file or assembly ... or one of its dependencies." - it's always a dependency of the library I'm trying to use that is the problem - not the library itself.


Below are the dependencies which are required:
"NETStandard.Library": "1.6.0",
"System.Net.NameResolution": "4.0.0",
"System.Reflection.TypeExtensions": "4.1.0",
"System.Threading.Tasks": "4.0.11",
"System.Net.Security": "4.3.0"
"Microsoft.Extensions.Caching.Abstractions": "1.0.0",
"Microsoft.Extensions.Caching.Memory": "1.0.0",
"Microsoft.Extensions.Logging.Abstractions": "1.0.0"
