### ISSUE TITLE
SFTP connection

### ISSUE THREAD

**Issue by PeterKottas** [sparkeh9/CoreFTP#21]
Hey mate, really nice lib. Works like a charm for ftp. I was wondering if it supports or if you are planning to support SFTP as well. So far I am having trouble connecting to these http://www.sftp.net/public-online-sftp-servers . Unless I am doing something wrong, it seems like it's not supported atm. 

This is my code :
`using (var ftpClient = new FtpClient(new FtpClientConfiguration
            {
                Host = config.FtpHost,
                Username = config.FtpUsername,
                Password = config.FtpPassword,
                Port = config.FtpPort,
                EncryptionType = FtpEncryption.Explicit,
                IgnoreCertificateErrors = true
            }))`

**Comment by sparkeh9** [comment]
We currently support FTP and FTP/S (over SSL). 

SFTP is an entirely different protocol which is badly named, because it is actually not related to FTP at all!

**Comment by PeterKottas** [comment]
Yeah that's right. I though this might be out of scope for you guys but makes sense to ask anyways I guess :) Anyways, good lib even without SFTP, carry on the good work and I've stared you up. 
For others looking into SFTP, I went with [SSH.NET](https://github.com/sshnet/SSH.NET) which is documented like *!%^ but it works so I am happy.
