### ISSUE TITLE
CoreFTP in ASP.NET Core MVC not working

### ISSUE THREAD

**Issue by josebarodriguez** [sparkeh9/CoreFTP#23]
Hi!
I'm trying to use your package CoreFTP but I get a error when it invoque the method LoginAsync():
"Value cannot be null. Parameter name: remoteEP".

The Code:
    using (var ftpClient = new FtpClient(new FtpClientConfiguration
            {
                Host = "ftp://ftp.udc.es",
                IgnoreCertificateErrors = true
            }))
            {
                try
                {
                    await ftpClient.LoginAsync();
                }
                catch (Exception ex)
                {
                    return ex.Message; // ERROR: Value cannot be null. Parameter name: remoteEP
                }
                ....

Any idea? Thanks.

**Comment by sparkeh9** [comment]
omit the protocol in the host string

**Comment by sparkeh9** [comment]
@josebarodriguez did that work?

**Comment by josebarodriguez** [comment]
Yes!. Thankyou!
But now I have another problem with folders... give me some days. I'm in spain holidays ;)

**Comment by josebarodriguez** [comment]
OK.
I am not able to navigate to the folder to get the list of files to use ListFilesAsync.
Is there any example or manual about it? Thank you.

**Comment by josebarodriguez** [comment]
I already discovered how to switch to a folder: ChangeWorkingDirectoryAsync
All is OK. 

          if (ftpClient.IsAuthenticated)
                {
                    await ftpClient.ChangeWorkingDirectoryAsync("folder/subfolder/...");
                    var archivos = ftpClient.ListFilesAsync();
                    foreach (var archivo in archivos.Result)
                    {
                        using (var ftpReadStream = await ftpClient.OpenFileReadStreamAsync(archivo.Name))
                        {
                         ...
          
Thank you very much!

**Comment by hussain-infotrack** [comment]
It would be nice if this was made more clear, or if an extra signature was added to have a filePath as a parameter in ListFilesAsync().
