### ISSUE TITLE
Problem do login

### ISSUE THREAD

**Issue by msmaldi** [sparkeh9/CoreFTP#24]
I trying open this file ftp://ftp.cetip.com.br/MediaCDI/20170420.txt

`            using (var ftpClient = new FtpClient(new FtpClientConfiguration
            {
                Host = "ftp://ftp.cetip.com.br/"
            }))
            {
                await ftpClient.LoginAsync();   // exception
                var files = await ftpClient.ListFilesAsync();
                
                await ftpClient.OpenFileReadStreamAsync("MediaCDI/20170420.txt");
            }
`

what is problem of my code?

**Comment by sparkeh9** [comment]
The host of a server does not include a scheme - drop the ftp:// from your URI.

**Comment by msmaldi** [comment]
Host = "ftp.cetip.com.br/" ?

Continue not working, you got the file?

**Comment by sparkeh9** [comment]
No slashes necessary - it is a hostname, not a URI :)

**Comment by msmaldi** [comment]
Thank you guy, work perfect.
