### ISSUE TITLE
Upload Stream

### ISSUE THREAD

**Issue by ricardobeckssa** [sparkeh9/CoreFTP#25]
Hello, how can I upload a stream?

**Comment by sparkeh9** [comment]
Everything is based on streams in this library - take a look at the link below.

https://github.com/sparkeh9/CoreFTP/blob/master/tests/CoreFtp.Tests.Integration/FtpClientTests/Files/When_opening_a_file_for_upload.cs#L44.

But basically,
`
var writeStream = await ftpClient.OpenFileWriteStreamAsync( "yourfile.jpg" );
await yourStream.CopyToAsync(writeStream)
`

**Comment by ricardobeckssa** [comment]
Thanks for your quick response. I'll to test
