### ISSUE TITLE
Could not load file or assembly 'System.Net.Security, Version=4.0.0.0

### ISSUE THREAD

**Issue by IngoBleile** [sparkeh9/CoreFTP#27]
I am getting "Could not load file or assembly 'System.Net.Security, Version=4.0.0.0" on my .NET Core 1.1 app (Windows 10 Creators Update, build 15063). What can I do?

**Comment by sparkeh9** [comment]
I'm afraid you'll have to give me more info than that to begin to figure out what's wrong 😛

The best thing would be to create a new empty project with no other dependencies using the same .NET version, and throw it on github so I can take a look :)

**Comment by IngoBleile** [comment]
With a new empty project it works perfectly, so I have to figure out what dependency is causing the problem. Thanks a lot! :)

**Comment by sparkeh9** [comment]
I'm afraid I don't know anything about UWP so CoreFTP has made no effort to target it.  Pull requests are always welcome :)
