### ISSUE TITLE
Actually requires .NETStandard >= 1.6.0

### ISSUE THREAD

**Issue by egeorgiades** [sparkeh9/CoreFTP#28]
This library won't work on UWP, and I believe the statement in the readme is inaccurate, as it actually requires .NETStandard >= 1.6.0 and not 1.3.

Since UWP can run up to 1.4, it won't work there.

**Comment by ZangiRider** [comment]
Hi,
Even with 1.6.0 Net standard you wont be able to use SSL./TLS Encryption. SslStream is available only in .NET Standard  2.0.

Im developing an FTP Library too but can't implement FTPS.

How did you do to get SslStream to work in .Net Standard 1.3?

**Comment by egeorgiades** [comment]
@ZangiRider I'm not using this as I needed a UWP edition, and anyway in my solution i'm not doing the SSL solution since I can't in UWP or Core.

**Comment by ZangiRider** [comment]
@egeorgiades  take a look at this https://github.com/ZangiRider/ftplib-netstandard
