### ISSUE TITLE
How to process hidden files.

### ISSUE THREAD

**Issue by basmilius** [sparkeh9/CoreFTP#40]
I'm trying to receive hidden files like .htaccess in my code. How can one do that?

**Comment by sparkeh9** [comment]
If your FTP server supports and is using the MLSD command, then it should already be listing hidden files already. If it isn't then there's nothing we can do to force it.

If however your FTP server is using the older LIST command, then you could modify code on this line to pass an optional "-a" argument, which will list hidden files (N.B. this argument is nonstandard and isn't technically in the spec)

Pull requests accepted and appreciated :)
