### ISSUE TITLE
Doesn't work in linux

### ISSUE THREAD

**Issue by NickG123** [sparkeh9/CoreFTP#5]
Attempting to call ftpClient.LoginAsync() on Linux results in the following exception:

```
This platform does not support connecting sockets to DNS endpoints via the instance Connect and ConnectAsync methods, due to the potential for a host name to map to multiple IP addresses and sockets becoming invalid for use after a failed connect attempt. Use the static ConnectAsync method, or provide to the instance methods the specific IPAddress desired.
```

This is the result of https://github.com/dotnet/corefx/issues/8768

**Comment by NickG123** [comment]
Awesome, thanks for the quick response and a great library overall!

**Comment by sparkeh9** [comment]
@NickG123 Can you confirm that this now works for your setup? :)

**Comment by NickG123** [comment]
Sorry, I am actually still running into problems.
The client appears to still be calling .connect using the hostname when opening a data socket: https://github.com/sparkeh9/CoreFTP/blob/d76b42984d330a142e766bdbf26d486bb966059c/src/CoreFtp/FtpClient.cs#L644
Thanks,
Nick

**Comment by sparkeh9** [comment]
Whoops - forgot to make the change in  the data socket too!

**Comment by sparkeh9** [comment]
@NickG123 Please check v1.1.7 on NuGet :)

**Comment by NickG123** [comment]
Seems to be working fine! Thanks a lot.
Nick
