### ISSUE TITLE
Upload file use Chinese path result garbled 

### ISSUE THREAD

**Issue by hamu01** [sparkeh9/CoreFTP#6]
The code always use ANSI encoding while result garbled when use Chinese path, I already fix this problem, but I don't have the push permission, how can I contribute my code?

**Comment by sparkeh9** [comment]
If you submit a pull request I will merge it in :)

**Comment by hamu01** [comment]
@sparkeh9 The problem is I can't push my local feature branch(because I don't have push permission), so I cann't submit pull request

**Comment by hamu01** [comment]
https://github.com/sparkeh9/CoreFTP/pull/7
Please review and merge my code, and I need a new version of CoreFTP in nuget, thank you.

**Comment by sparkeh9** [comment]
Plerase see https://www.nuget.org/packages/CoreFtp/1.2.0
