### ISSUE TITLE
Support FTP over SSL

### ISSUE THREAD

**Issue by sparkeh9** [sparkeh9/CoreFTP#8]
Need to support FTP over SSL

**Comment by kwilliamssbs** [comment]
So far, yours is the only .NET Core FTP library we've found that can replace our old FTP library, so if you need or want any help on this one (it's the last requirement for us), then let me know!

**Comment by sparkeh9** [comment]
I'm working on it as we speak :D, I have the control connection encrypted using TLS (implicit and explicit), just need to get the data connection doing the same and it should be good to go.

**Comment by sparkeh9** [comment]
👍 That is why I started writing this library, I noticed Microsoft had removed all the built in stuff for it, and nothing was targeting anything other than the desktop CLR
